
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hi">
      <body
        className="min-h-screen flex flex-col  bg-gradient-to-r from-gray-100 via-gray-100 to-purple-50" >
        {children}
      </body>
    </html>
  );
}
